SELECT F.NUMERO_FACTURA,F.FECHA,F.ID_CLIENTE,E.NOMBRES,F.BASE0,F.BASEIMPO,F.IVA,F.TOTAL, F.ELIMINADO,F.TIPO_PAGO,F.ID_USUARIO
FROM FACTURA F, ESTUDIANTE E 
WHERE F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO=0 
AND F.ID_USUARIO = "PCHICAIZA"
AND F.FECHA>="2012-01-01" AND F.FECHA<="2012-01-31"
ORDER BY F.NUMERO_FACTURA,F.FECHA