SELECT F.NUMERO_FACTURA,"A100" AS FACULTAD, "05" AS DEPAR,"R" AS ESTADO,F.FECHA AS FECHA, "05" AS TIPOS,
F.ID_CLIENTE AS CEDULA,"V" AS TIPO ,E.NOMBRES AS NOMBRES,"0" AS V1,"0" AS UNO,"0" AS V2,"0" AS DOS,"0" AS V3,"0" AS TRES,"0" AS V4,"0" AS CUATRO,
"0" AS V5,"0" AS CINCO,"0" AS V6,"0" AS SEIS,"0" AS V7,"0" AS SIETE,"0" AS V8,"0" AS OCHO,"0" AS V9,"0" AS NUEVE,
F.BASE0,F.BASEIMPO,F.IVA,(F.TOTAL-F.IVA) AS total,F.ELIMINADO AS BORRADO,F.TIPO_PAGO AS TIPAGO,F.FECHA AS FDEPO,
"A" AS CHEQUE,"0" AS CODIROL,"01" AS TICOMP, "01" AS TIVENTA,F.ZONA, F.FACU AS FACU,F.AUTORIZA
FROM FACTURA F, ESTUDIANTE E
WHERE F.ID_USUARIO = "SCHICAIZA"
AND F.FECHA >="2012-01-01" AND F.FECHA<="2012-01-31"
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO = 0


SELECT F.NUMERO_FACTURA,"A100" AS FACULTAD, "05" AS DEPAR,"R" AS ESTADO,F.FECHA AS FECHA, "05" AS TIPOS,
F.ID_CLIENTE AS CEDULA,"V" AS TIPO ,E.NOMBRES AS NOMBRES,"0" AS V1,"0" AS UNO,"0" AS V2,"0" AS DOS,"0" AS V3,"0" AS TRES,"0" AS V4,"0" AS CUATRO,
"0" AS V5,"0" AS CINCO,"0" AS V6,"0" AS SEIS,"0" AS V7,"0" AS SIETE,"0" AS V8,"0" AS OCHO,"0" AS V9,"0" AS NUEVE,
F.BASE0,F.BASEIMPO,F.IVA,(F.TOTAL-F.IVA) AS total,F.ELIMINADO AS BORRADO,F.TIPO_PAGO AS TIPAGO,F.FECHA AS FDEPO,
"A" AS CHEQUE,"0" AS CODIROL,"01" AS TICOMP, "01" AS TIVENTA,F.ZONA, F.FACU AS FACU,F.AUTORIZA
FROM FACTURA F, ESTUDIANTE E
WHERE F.ID_USUARIO IN ("PCHICAIZA")
AND F.FECHA >="2012-01-01" AND F.FECHA<="2012-01-31"
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO = 0

SELECT F.FECHA,SUM(F.BASE0), SUM(F.BASEIMPO),SUM(F.IVA)
FROM FACTURA F
WHERE F.ID_USUARIO = "PCHICAIZA"
AND F.FECHA >="2012-01-01" AND F.FECHA<="2012-01-31"
GROUP BY F.FECHA