SELECT D.ID,F.NUMERO_FACTURA,E.CEDULA,E.NOMBRES,D.VU,D.ID_PARTIDA,P.DESCRIPCION,D.ID_ARANCEL,F.ES_TAR_TIPO,F.ES_TAR_RECAP
FROM PARTIDA P,DETALLE D,FACTURA F, ESTUDIANTE E
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND F.FECHA>='2012-02-06' 
AND F.FECHA<='2012-02-06' 
AND F.TIPO_PAGO = 6
AND F.ID_USUARIO = "PCHICAIZA"
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO = 0
