SELECT D.ID,P.PARTIDA,P.DESCRIPCION,A.NOMBRE,D.VU,D.ID_FACTURA,D.ID
FROM ARANCEL_PARTIDA AP, PARTIDA P, ARANCEL A,DETALLE D
WHERE P.PARTIDA = AP.ID_PARTIDA
AND AP.ID_ARANCEL = A.ID 
AND D.ID_ARANCEL = AP.ID_ARANCEL 
AND D.ID_PARTIDA = AP.ID_PARTIDA

SELECT * FROM PARTIDA WHERE PARTIDA ="2012.176.1000.0027.130111.002"

SELECT * FROM ARANCEL_PARTIDA WHERE ID_PARTIDA = "2012.176.1000.0027.130111.002"


SELECT PA.TIPO_PARTIDA,P.ID,SUM(D.VU)
FROM PREDIOS P, RECAUDADOR R,FACTURA F,DETALLE D, ARANCEL_PARTIDA AP,PARTIDA PA
WHERE P.ID = R.IDP
AND R.IDU = F.ID_USUARIO 
AND F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = AP.ID_PARTIDA 
AND AP.ID_PARTIDA = PA.PARTIDA
AND F.FECHA = "2012-01-11"
GROUP BY PA.TIPO_PARTIDA

///
REPORTE POR PARTIDA Y ARANCEL PARA BALBINA 
SOLO CAMBIAR FECHAS 
////

SELECT P.PARTIDA ,P.DESCRIPCION,D.VU AS TOTAL,D.CANTIDAD AS CANTIDAD,D.IVA AS IVA,F.NUMERO_FACTURA,F.ID_USUARIO,F.ID_CLIENTE,E.NOMBRES
FROM PARTIDA P,DETALLE D,FACTURA F, ESTUDIANTE E
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ID_CLIENTE = E.CEDULA
AND F.ELIMINADO = 0
AND F.FECHA>='2012-01-13' 
AND F.FECHA<='2012-01-13' 
ORDER BY P.PARTIDA
///


AND F.ID_USUARIO = 'SCHICAIZA' 
//
REPORTE POR ARANCEL 
//
SELECT d.ID_ARANCEL,a.NOMBRE,SUM(d.VU) AS total,COUNT(d.CANTIDAD) AS cantidad,SUM(d.IVA) AS iva 
FROM detalle d,arancel a,factura f 
WHERE d.ID_ARANCEL = a.ID AND a.ACTIVA =1 AND d.ID_FACTURA = f.NUMERO_FACTURA 
AND f.FECHA>='2012-01-11' AND 
f.FECHA<='2012-01-11' AND f.ELIMINADO = 0 AND F.ID_USUARIO = 'SCHICAIZA' 
GROUP BY d.ID_ARANCEL 

SELECT P.PARTIDA ,P.DESCRIPCION,D.VU AS TOTAL,D.CANTIDAD AS CANTIDAD,D.IVA AS IVA,F.NUMERO_FACTURA
FROM PARTIDA P,DETALLE D,FACTURA F
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND f.FECHA>='2012-01-11' 
AND F.FECHA<='2012-01-11' 
AND F.ID_USUARIO = 'SCHICAIZA' 
ORDER BY P.PARTIDA



SELECT P.PARTIDA ,P.DESCRIPCION,D.VU AS TOTAL,D.CANTIDAD AS CANTIDAD,D.IVA AS IVA,F.NUMERO_FACTURA
FROM PARTIDA P,DETALLE D,FACTURA F
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND f.FECHA>='2012-01-11' 
AND F.FECHA<='2012-01-11' 
AND F.ID_USUARIO = 'SCHICAIZA' 
GROUP BY P.PARTIDA
ORDER BY P.PARTIDA


//////
SELECT P.PARTIDA,D.VU,D.ID_FACTURA,D.ID,F.ID_USUARIO,F.FECHA,P.PARTE5,P.PARTE1,P.PARTE2,P.PARTE3,P.PARTE4,P.PARTE6, 
A.ID AS ID_ARANCEL,A.NOMBRE,D.IVA,A.CUOTA,P.DESCRIPCION ,F.ID_CLIENTE,E.CEDULA,E.NOMBRES
FROM ARANCEL_PARTIDA AP, PARTIDA P, ARANCEL A,DETALLE D,FACTURA F ,ESTUDIANTE E
WHERE P.PARTIDA = AP.ID_PARTIDA AND AP.ID_ARANCEL = A.ID AND D.ID_ARANCEL = AP.ID_ARANCEL 
AND D.ID_PARTIDA = AP.ID_PARTIDA AND D.ID_FACTURA = F.NUMERO_FACTURA 
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO=0
AND F.FECHA = '2012-01-17' ORDER BY P.PARTE5,P.DESCRIPCION ASC


SELECT * FROM ESTUDIANTE WHERE CEDULA ="1804065751"

//
PARA EL LISTADO DE CUENTAS POR CORBRAR 
///
SELECT D.ID,F.NUMERO_FACTURA,E.CEDULA,E.NOMBRES,D.VU,D.ID_PARTIDA,P.DESCRIPCION,D.ID_ARANCEL,F.ID_USUARIO
FROM PARTIDA P,DETALLE D,FACTURA F, ESTUDIANTE E
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND F.FECHA>='2012-02-08' 
AND F.FECHA<='2012-02-08' 
AND F.TIPO_PAGO = 3
AND F.ES_CUE_COB_CEDULA = E.CEDULA 
AND E.ES_EMPLEADO= 1 AND E.ES_EMPLEADO = 1
ORDER BY P.PARTIDA

//////
revision de arancel y partida 
///////

SELECT * FROM ARANCEL_PARTIDA WHERE ID_ARANCEL = 1 AND ID_PARTIDA = "2012.176.1000.0027.130111.002"


SELECT * FROM DETALLE D,FACTURA F WHERE D.ID_ARANCEL = 1 AND D.ID_PARTIDA = "2012.176.1000.0027.130111.002" 
AND F.NUMERO_FACTURA = D.ID_FACTURA 

UPDATE DETALLE D SET ID_PARTIDA = "2012.176.1000.0020.130111.002"
WHERE D.ID_ARANCEL = 1 AND D.ID_PARTIDA = "2012.176.1000.0027.130111.002" 

SELECT *
FROM FACTURA F,DETALLE D
WHERE F.NUMERO_FACTURA = D.ID_FACTURA 
AND F.FECHA = "2012-01-21" AND D.ID_ARANCEL = 187 AND F.NUMERO_FACTURA = "531949"

SELECT * FROM PARTIDA WHERE PARTIDA ="2012.176.1000.0023.130111.002"
//////

SELECT *
FROM PARTIDA WHERE DESCRIPCION LIKE "%CEPOS%"

///////////////
arancel partida programa
///////////////
SELECT P.PARTE3,P.PARTE4,P.DESCRIPCION
FROM PARTIDA P, PROGRAMA PRO
WHERE P.FACULTAD = PRO.ID_FACULTAD AND P.DESCRIPCION_PROGRAMA = PRO.CODIGO
AND P.PARTE3!="0000" AND P.PARTE4!="0000" ORDER BY PRO.ID_FACULTAD

SELECT P.PARTE3,P.PARTE4
FROM PARTIDA P, PROGRAMA PRO
WHERE P.DESCRIPCION_PROGRAMA = PRO.CODIGO

SELECT * FROM PARTIDA WHERE DESCRIPCION  LIKE "%DEDI%"


////////////////////////////
TARJETAS 
///////////////////////
SELECT D.ID,F.NUMERO_FACTURA,E.CEDULA,E.NOMBRES,D.VU,D.ID_PARTIDA,P.DESCRIPCION,D.ID_ARANCEL,F.ES_TAR_TIPO,F.ES_TAR_RECAP,F.ID_USUARIO
FROM PARTIDA P,DETALLE D,FACTURA F, ESTUDIANTE E
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND F.FECHA>='2012-02-08' 
AND F.FECHA<='2012-02-08' 
AND F.TIPO_PAGO = 6
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO = 0
////////////////////////
IVA 
/////////////////////////

SELECT D.ID,F.NUMERO_FACTURA,E.CEDULA,E.NOMBRES,D.VU,D.ID_PARTIDA,P.DESCRIPCION,D.ID_ARANCEL,D.IVA,F.ID_USUARIO
FROM PARTIDA P,DETALLE D,FACTURA F, ESTUDIANTE E
WHERE F.NUMERO_FACTURA = D.ID_FACTURA
AND D.ID_PARTIDA = P.PARTIDA
AND F.ELIMINADO = 0
AND F.FECHA>='2012-02-08' 
AND F.FECHA<='2012-02-08' 
AND F.ID_CLIENTE = E.CEDULA AND E.ES_EMPLEADO = 0
AND D.IVA>0