SELECT COUNT(ID_USUARIO) ,ID_USUARIO FROM FACTURA GROUP BY ID_USUARIO

SELECT COUNT(ID_USUARIO) ,ID_USUARIO FROM FACTURA WHERE FECHA <="2012-01-31"
GROUP BY ID_USUARIO

SELECT * FROM FACTURA WHERE ELIMINADO = 1

